# Screens
SCREEN_PIN_ENTRY = 'pin_entry'
SCREEN_OTP_ENTRY = 'otp_entry'
SCREEN_CONFIRMATION = 'confirmation'
SCREEN_WELCOME = 'welcome'
SCREEN_ERROR = 'error'
SCREEN_IDLE = 'idle'
SCREEN_SUCCESS = 'success'
SCREEN_STAFF_PIN = 'staff_pin'
SCREEN_STAFF_CHECKLIST = 'staff_checklist'
SCREEN_BATCH_SUMMARY = 'batch_summary'
SCREEN_BATCH_PROGRESS = 'batch_progress'
SCREEN_PIN_SETUP = 'pin_setup'
SCREEN_LOCKED = 'locked'
SCREEN_REG_ENTRY = 'reg_entry'