"""
UI Constants

Shared screen names and length limits for the kiosk flow.
"""

SCREEN_IDLE = "idle"
SCREEN_REG_ENTRY = "reg_entry"
SCREEN_OTP_ENTRY = "otp_entry"
SCREEN_PIN_ENTRY = "pin_entry"
SCREEN_PIN_SETUP = "pin_setup"
SCREEN_WAIT = "wait"
SCREEN_CONFIRMATION = "confirmation"
SCREEN_ERROR = "error"
SCREEN_LOCKED = "locked"

REG_NUMBER_FORMAT = "XXXX-XX-XXXXX"
REG_NUMBER_LENGTH = 13
REG_NUMBER_DIGITS = 11
OTP_LENGTH = 6
PIN_LENGTH = 4

LOOKUP_MAX_TRIES = 3
OTP_MAX_TRIES = 3
PIN_MAX_TRIES = 3

SESSION_TIMEOUT_SECONDS = 15
LOCKOUT_SCREEN_SECONDS = 5
CONFIRMATION_SCREEN_SECONDS = 15
